server:
  port: 9099
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local?useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
logging:
  level:
    root: debug